import { ArrowRight, BookOpenCheck, CalendarCheck2, ChevronRight, Clock3, Flame, Lightbulb, Play, Sparkles, Target, Trophy, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { dailyLessons, weekData } from '../data/mock-data';

export function Dashboard() {
  return <div className="page dashboard-page">
    <section className="hero-card">
      <div className="hero-copy"><span className="eyebrow"><Sparkles size={14}/> Chủ nhật, 20 tháng 9</span><h1>Chào buổi sáng, Huyền <span>👋</span></h1><p>Hôm nay bạn muốn học gì? Mỗi bước nhỏ đều đưa bạn gần hơn tới mục tiêu N4.</p><div className="hero-actions"><Link to="/quiz" className="primary-button"><Play size={17} fill="currentColor"/> Tiếp tục học</Link><span><strong>JLPT N4</strong> · 68% hoàn thành</span></div><div className="hero-progress"><i style={{width:'68%'}}/></div></div>
      <div className="goal-orbit"><div className="orbit-ring"><span><strong>68%</strong><small>Mục tiêu N4</small></span></div><div className="floating-badge"><Flame size={18}/><strong>12 ngày</strong></div></div>
    </section>

    <div className="section-heading"><div><span className="section-kicker">Daily learning</span><h2>Bài học hôm nay</h2></div><button className="text-button">Xem lộ trình <ArrowRight size={16}/></button></div>
    <section className="lesson-grid">{dailyLessons.map((lesson, index) => <article className={`lesson-card tone-${lesson.tone}`} key={lesson.title}><div className="lesson-top"><span className="lesson-icon">{lesson.icon}</span><span className="lesson-count">0{index+1}</span></div><h3>{lesson.title}</h3><p>{lesson.detail}</p><div className="mini-progress"><i style={{width:`${lesson.progress}%`}}/></div><button onClick={() => alert(`Bắt đầu ${lesson.title}`)}>Học ngay <ChevronRight size={16}/></button></article>)}</section>

    <section className="dashboard-grid">
      <article className="panel progress-panel"><div className="panel-heading"><div><span className="section-kicker">7 ngày gần nhất</span><h2>Nhịp học của bạn</h2></div><select aria-label="Chọn thời gian"><option>Tuần này</option><option>Tuần trước</option></select></div><div className="chart-wrap"><div className="chart-y"><span>90</span><span>60</span><span>30</span><span>0</span></div><div className="bar-chart">{weekData.map((value,i)=><div className="bar-column" key={i}><div className="bar" style={{height:`${value}%`}}><span>{value}</span></div><small>{['T2','T3','T4','T5','T6','T7','CN'][i]}</small></div>)}</div></div><div className="chart-legend"><span><i className="dot indigo"/>42 phút trung bình</span><span><i className="dot coral"/>+18% so với tuần trước</span></div></article>
      <aside className="right-stack"><article className="panel stat-summary"><span className="section-kicker">Hôm nay</span><h2>Thành tích</h2><div className="metric-list"><div><span className="metric-icon coral"><Clock3 size={19}/></span><p><strong>42 phút</strong><small>Thời gian học</small></p></div><div><span className="metric-icon indigo"><Zap size={19}/></span><p><strong>180 XP</strong><small>Đã nhận hôm nay</small></p></div><div><span className="metric-icon gold"><Target size={19}/></span><p><strong>4 / 6</strong><small>Nhiệm vụ hoàn tất</small></p></div></div></article><article className="mission-card"><div><Trophy size={22}/><span>Nhiệm vụ trong ngày</span></div><h3>Kanji Explorer</h3><p>Học thêm 4 Kanji để nhận 50 XP.</p><div className="mission-progress"><i style={{width:'60%'}}/></div><span>6 / 10 Kanji</span></article></aside>
    </section>
    <section className="continue-strip"><span className="continue-icon"><BookOpenCheck/></span><div><span className="section-kicker">Tiếp tục từ hôm qua</span><h3>Ngữ pháp N4 · Bài 08</h3><p>〜なければならない · Bắt buộc phải...</p></div><Link to="/grammar" className="round-arrow"><ArrowRight/></Link></section>
    <section className="dashboard-lower">
      <article className="panel weekly-plan"><div className="panel-heading"><div><span className="section-kicker">Kế hoạch tuần</span><h2>Mục tiêu của Huyền</h2></div><span className="week-score">76%</span></div><div className="week-progress"><i style={{width:'76%'}}/></div><div className="week-days">{['T2','T3','T4','T5','T6','T7','CN'].map((day,index)=><div className={index<5?'done':index===6?'today':''} key={day}><span>{index<5?<CalendarCheck2 size={16}/>:day}</span><small>{index<5?'Đã học':index===6?'Hôm nay':'Nghỉ'}</small></div>)}</div><footer><span>4 giờ 35 phút đã học</span><strong>Còn 1 giờ 25 phút</strong></footer></article>
      <article className="panel recommendations"><div className="panel-heading"><div><span className="section-kicker">Gợi ý cho bạn</span><h2>Nên học tiếp</h2></div><Lightbulb size={21}/></div><Link to="/kanji"><span className="recommend-symbol">旅</span><div><strong>Kanji chủ đề du lịch</strong><small>8 chữ · khoảng 12 phút</small></div><ChevronRight/></Link><Link to="/listening"><span className="recommend-symbol audio">聴</span><div><strong>Hội thoại tại nhà ga</strong><small>N4 · 8 phút nghe</small></div><ChevronRight/></Link><Link to="/flashcards"><span className="recommend-symbol cards">復</span><div><strong>Ôn 18 thẻ sắp quên</strong><small>Dựa trên lượt học gần đây</small></div><ChevronRight/></Link></article>
    </section>
    <section className="panel activity-panel"><div className="panel-heading"><div><span className="section-kicker">Hoạt động gần đây</span><h2>Những gì bạn vừa hoàn thành</h2></div><Link to="/progress" className="text-button">Xem tất cả <ArrowRight size={16}/></Link></div><div className="activity-list"><div><span className="activity-dot success"><CheckCircleIcon/></span><p><strong>Hoàn thành Quiz từ vựng N4</strong><small>8/10 câu đúng · +80 XP</small></p><time>09:42</time></div><div><span className="activity-dot indigo"><BookOpenCheck size={16}/></span><p><strong>Học bài ngữ pháp 〜ながら</strong><small>Hoàn thành bài 07</small></p><time>Hôm qua</time></div><div><span className="activity-dot coral"><Flame size={16}/></span><p><strong>Đạt chuỗi 12 ngày học</strong><small>Kỷ lục mới của bạn</small></p><time>Hôm qua</time></div></div></section>
  </div>;
}

function CheckCircleIcon(){return <span aria-hidden="true">✓</span>}
