import { useMemo, useState } from 'react';
import { Bookmark, Check, Plus, Search, Volume2 } from 'lucide-react';
import { grammar, kanji, vocabulary } from '../data/mock-data';

export function VocabularyPage() { const [query,setQuery]=useState(''); const [saved,setSaved]=useState<string[]>([]); const items=useMemo(()=>vocabulary.filter(v=>`${v.word}${v.reading}${v.meaning}`.toLowerCase().includes(query.toLowerCase())),[query]); return <ResourcePage title="Từ vựng" subtitle="Xây nền từ vựng vững chắc theo từng cấp JLPT"><Filters query={query} setQuery={setQuery}/><div className="resource-grid">{items.map(v=><article className="vocab-card" key={v.word}><div className="card-actions"><span className="level-tag">{v.level}</span><button onClick={()=>alert(`Phát âm: ${v.reading}`)}><Volume2 size={18}/></button></div><h2>{v.word}</h2><p className="reading">{v.reading} · <i>{v.romaji}</i></p><strong className="meaning">{v.meaning}</strong><span className="word-type">{v.type}</span><div className="example"><small>例文</small><p>{v.example}</p><span>{v.translation}</span></div><button className={saved.includes(v.word)?'saved action-button':'action-button'} onClick={()=>setSaved(s=>s.includes(v.word)?s.filter(x=>x!==v.word):[...s,v.word])}>{saved.includes(v.word)?<Check size={17}/>:<Plus size={17}/>} {saved.includes(v.word)?'Đã thêm':'Thêm vào flashcard'}</button></article>)}</div></ResourcePage> }

export function KanjiPage() { return <ResourcePage title="Kanji" subtitle="Hiểu chữ Hán qua âm đọc, bộ nét và từ ứng dụng"><Filters/><div className="resource-grid kanji-grid">{kanji.map(k=><article className="kanji-card" key={k.char}><div className="kanji-head"><span>{k.char}</span><i>{k.level}</i></div><div className="kanji-readings"><p><small>ONYOMI</small>{k.on}</p><p><small>KUNYOMI</small>{k.kun}</p></div><div className="kanji-meta"><strong>{k.meaning}</strong><span>{k.strokes} nét</span></div><div className="word-chips">{k.words.map(w=><span key={w}>{w}</span>)}</div><div className="button-row"><button onClick={()=>alert('Mở thứ tự nét')}>Thứ tự nét</button><button className="solid" onClick={()=>alert('Mở vùng luyện viết')}>Luyện viết</button></div></article>)}</div></ResourcePage> }

export function GrammarPage() { const [bookmarks,setBookmarks]=useState<string[]>([]); return <ResourcePage title="Ngữ pháp" subtitle="Nắm cấu trúc qua ví dụ tự nhiên và giải thích bằng tiếng Việt"><Filters/><div className="grammar-list">{grammar.map(g=><article className="grammar-card" key={g.pattern}><div className="grammar-index"><span>{g.level}</span><strong>{g.pattern}</strong></div><div className="grammar-body"><div><small>Ý NGHĨA</small><h3>{g.meaning}</h3></div><div><small>CẤU TRÚC</small><code>{g.structure}</code></div><blockquote><p>{g.example}</p><span>{g.translation}</span></blockquote></div><button className={bookmarks.includes(g.pattern)?'bookmark active':'bookmark'} onClick={()=>setBookmarks(s=>s.includes(g.pattern)?s.filter(x=>x!==g.pattern):[...s,g.pattern])}><Bookmark size={19} fill={bookmarks.includes(g.pattern)?'currentColor':'none'}/></button></article>)}</div></ResourcePage> }

function ResourcePage({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}) { return <div className="page"><header className="page-title"><div><span className="section-kicker">Thư viện học tập</span><h1>{title}</h1><p>{subtitle}</p></div><div className="page-title-mark">日本語</div></header>{children}</div> }
function Filters({query='',setQuery}:{query?:string;setQuery?:(v:string)=>void}) { return <div className="filters"><label><Search size={18}/><input value={query} onChange={e=>setQuery?.(e.target.value)} placeholder="Tìm kiếm nội dung..."/></label><select><option>Tất cả cấp độ</option>{['N5','N4','N3','N2','N1'].map(x=><option key={x}>{x}</option>)}</select><select><option>Tất cả chủ đề</option><option>Đời sống</option><option>Trường học</option><option>Công việc</option></select></div> }

export function ComingPage({title,icon='学'}:{title:string;icon?:string}) { return <div className="page"><div className="coming-page"><span>{icon}</span><p className="section-kicker">Không gian học tập</p><h1>{title}</h1><p>Tính năng đang được hoàn thiện trong cùng hệ thống thiết kế. Bạn có thể quay lại Dashboard để tiếp tục lộ trình hôm nay.</p><a href="/">Về Dashboard</a></div></div> }
