import { useState } from 'react';
import { ArrowRight, CheckCircle2, Copy, RotateCcw, Send, Volume2, XCircle } from 'lucide-react';

export function FlashcardsPage() { const [flipped,setFlipped]=useState(false); const [rated,setRated]=useState(''); return <div className="page practice-page"><header className="page-title"><div><span className="section-kicker">Ôn tập thông minh</span><h1>Flashcard</h1><p>Bộ từ vựng N4 · 12 / 30</p></div><button className="ghost-button"><RotateCcw size={17}/> Bắt đầu lại</button></header><div className="flashcard-stage"><button className={`flashcard ${flipped?'flipped':''}`} onClick={()=>setFlipped(v=>!v)}><div className="flash-face front"><span>日本語</span><small>Nhấn để xem đáp án</small></div><div className="flash-face back"><span>にほんご</span><i>nihongo</i><strong>Tiếng Nhật</strong><p>日本語を勉強しています。</p><small>Tôi đang học tiếng Nhật.</small></div></button><div className="rating-row">{[['Again','Chưa nhớ'],['Hard','Khó'],['Good','Tốt'],['Easy','Dễ']].map(([key,label])=><button className={rated===key?'selected':''} key={key} onClick={()=>{setRated(key);setFlipped(false)}}><kbd>{key[0]}</kbd><span>{label}</span></button>)}</div></div></div> }

export function QuizPage() { const [answer,setAnswer]=useState(''); const correct='経験'; const checked=Boolean(answer); return <div className="page quiz-page"><header className="quiz-header"><div><span className="section-kicker">Quiz từ vựng · N4</span><h1>Câu hỏi 3 <span>/ 10</span></h1></div><div className="quiz-progress"><i style={{width:'30%'}}/></div></header><section className="question-card"><span className="question-type">CHỌN NGHĨA ĐÚNG</span><h2>“Kinh nghiệm” trong tiếng Nhật là gì?</h2><div className="answers">{['約束','経験','準備','連絡'].map(a=><button disabled={checked} onClick={()=>setAnswer(a)} className={checked?(a===correct?'correct':a===answer?'wrong':''):''} key={a}><span>{a}</span>{checked&&a===correct&&<CheckCircle2/>}{checked&&a===answer&&a!==correct&&<XCircle/>}</button>)}</div>{checked&&<div className={answer===correct?'feedback success':'feedback error'}><strong>{answer===correct?'Chính xác!':'Chưa đúng'}</strong><p>経験（けいけん）có nghĩa là kinh nghiệm. Ví dụ: 日本で働いた経験があります。</p><button onClick={()=>setAnswer('')}>Câu tiếp theo <ArrowRight size={17}/></button></div>}</section></div> }

export function TutorPage() { const [text,setText]=useState(''); const [messages,setMessages]=useState([{who:'user',text:'昨日友達と映画を見ました。'},{who:'ai',text:'Câu của bạn hoàn toàn đúng。\n昨日 = hôm qua\n友達と = với bạn\n映画を見ました = đã xem phim'}]); const send=()=>{if(!text.trim())return;setMessages(m=>[...m,{who:'user',text},{who:'ai',text:'Câu này tự nhiên và đúng ngữ pháp. Mình đã lưu ý ngữ cảnh để giải thích kỹ hơn ở lượt tiếp theo.'}]);setText('')}; return <div className="page tutor-page"><header className="page-title"><div><span className="section-kicker">Trợ lý học tập</span><h1>AI Japanese Tutor</h1><p>Hỏi ngữ pháp, dịch câu hoặc luyện hội thoại.</p></div><span className="ai-status"><i/> AI sẵn sàng</span></header><div className="chat-shell"><aside className="chat-tools"><strong>Chế độ học</strong>{['Hội thoại','Sửa ngữ pháp','Dịch','Giải thích Kanji','Roleplay'].map((x,i)=><button className={i===1?'active':''} key={x}>{x}</button>)}</aside><section className="chat-panel"><div className="messages">{messages.map((m,i)=><div className={`message ${m.who}`} key={i}><span>{m.who==='ai'?'未':'HN'}</span><div><p>{m.text}</p>{m.who==='ai'&&<div className="message-actions"><button><Volume2 size={15}/> Nghe</button><button><Copy size={15}/> Sao chép</button></div>}</div></div>)}</div><div className="chat-input"><button className="furigana-toggle">ふ Furigana</button><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Nhập câu tiếng Nhật hoặc câu hỏi..."/><button className="send-button" onClick={send}><Send size={18}/></button></div><small className="ai-note">AI có thể mắc lỗi. Hãy đối chiếu nội dung quan trọng với nguồn học liệu.</small></section></div></div> }

export function ProgressPage() { return <div className="page"><header className="page-title"><div><span className="section-kicker">Learning analytics</span><h1>Tiến độ học tập</h1><p>Nhìn lại nỗ lực và giữ nhịp học bền vững.</p></div></header><div className="stats-grid">{[['12','Ngày streak'],['32h 40m','Tổng thời gian'],['486','Từ đã học'],['128','Kanji đã học'],['62%','Tiến độ N4']].map(([n,l])=><article key={l}><strong>{n}</strong><span>{l}</span></article>)}</div><section className="panel radar-panel"><div><span className="section-kicker">Kỹ năng</span><h2>Bức tranh năng lực</h2><p>Từ vựng và đọc hiểu đang tiến triển tốt. Hãy dành thêm thời gian cho nghe và Kanji.</p></div><div className="skill-bars">{[['Từ vựng',82],['Kanji',64],['Ngữ pháp',74],['Nghe',48],['Đọc',69]].map(([l,v])=><div key={String(l)}><span>{l}<b>{v}%</b></span><i><em style={{width:`${v}%`}}/></i></div>)}</div></section></div> }
